name: Ondemand Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:  
  test:
    runs-on: self-hosted  
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
      - name: Build 
        run: dotnet build eShop.Web.slnf
      - name: Test
        run: dotnet test eShop.Web.slnf
